# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dnepr Lambda Club
email: support@lambdaclub.net
description: >
  В&nbsp;последнее время в&nbsp;мире разработчиков сложилось пока
  не&nbsp;такое большое, но&nbsp;растущее сообщество тех, кто так
  или иначе в&nbsp;своей профессиональной деятельности предпочитает
  функциональное программирование в&nbsp;разных его ипостасях. Зачастую,
  даже независимо от&nbsp;выбранного языка программирования. На&nbsp;основании
  такого опыта мы&nbsp;решили организовать шестую встречу
  &laquo;лямбдаклуба в Днепре&raquo;. Конечно&nbsp;же,
  слово &laquo;лямбда&raquo; в&nbsp;названии подразумевает темы так
  или иначе связанных с&nbsp;функциональным программированием,
  но&nbsp;это совсем не&nbsp;обязательное условие. Мы&nbsp;практичные,
  а&nbsp;потому мультипарадигменные.
baseurl: ""
url: "http://lambdaclub.net"
name: "lambdaclub.net"
# gems:
#   - jekyll-redirect-from

# Build settings
markdown: kramdown
